### ISSUE TITLE
Follow multiple redirects (maybe with a configurable max)

### ISSUE THREAD

**Issue by wouterlemcke** [OP-Engineering/link-preview-js#135]
It would be great if we could make the library follow multiple redirects.
The issue we're encountering is that we try to generate a preview for a link that has 2 redirects on it
First from HTTP to HTTPS and then a 'normal' redirect to another path.

Unfortunately we don't control the source of this link, so we cannot change it.

**Comment by ospfranco** [comment]
PRs are welcome

**Comment by george-i** [comment]
I thought that if we set the
`followRedirects: 'manual'` it is possible to handle the max redirects in the `handleRedirects` option.
However, it seems that no matter the value I set for `followRedirects` option I get the message `uri requested responds with a redirect, redirect mode is set to error`

**Comment by george-i** [comment]
Maybe is possible if you set `followRedirects: 'manual'` and then in `handleRedirects` you count the number of redirects,
When your desired maximum redirects is reached, it should return a reject,

I haven't tested this yet, but it makes sense.
I didn't had a way to test.

**Comment by edehlol** [comment]
@george-i It seems like the library only allows 1 redirect to happen.

**Comment by ospfranco** [comment]
Back from a long vacation, looks like some of you are using the library in a paid product, would gladly implement this for you guys for a small fee/sponsorship.

**Comment by ospfranco** [comment]
Seems nobody was willing to open a PR. Going to close this. Feel free to open a new ticket if necessary.
