### ISSUE TITLE
Doesn't work when deployed

### ISSUE THREAD

**Issue by NikhilKalloli** [OP-Engineering/link-preview-js#153]
I'm trying to deploy it as an API which I can use in my application but it doesn't work. I think the issue is because of:    
`You cannot preview (fetch) another web page from YOUR web page. This is an intentional security feature of browsers called CORS`   

I've enabled CORS in my API(where i actually use this package) but still it fails.
Can anyone please address this or any workaround is higly appreciated.

**Comment by ospfranco** [comment]
Read again how CORS work, you cannot "enable" it, other websites prevent cross requests from other domains, that's the point of it.

**Comment by NikhilKalloli** [comment]
Is there any workaround ?
Does using header agents to mimc the browser work?
Pardon me If I sound naive.

Thanks for responding.

**Comment by ospfranco** [comment]
No, there is no workaround, this is a security feature of browsers. Go read about CORS.
