### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by IrfanMaulana00** [OP-Engineering/link-preview-js#156]
I'm trying use the example on my laptop, but i got error MODULE_NOT_FOUND, i was install the library
```bash
npm install link-preview-js
```

<img width="652" alt="Screenshot_171" src="https://github.com/user-attachments/assets/0acc4f6d-de17-4115-be02-4a7524f75f14">

**Comment by ospfranco** [comment]
Try with the latest release please `3.0.12`

**Comment by IrfanMaulana00** [comment]
great, thank you
