### ISSUE TITLE
Some Facebook Reels thumbnail images are being cropped

### ISSUE THREAD

**Issue by MarwaKhaledMohamed** [OP-Engineering/link-preview-js#157]
Hi,

**Describe the bug**
When processing Facebook Reel URLs, the image is sometimes retrieved with an incorrect aspect ratio, typically rendering them as square (1:1) rather than the intended rectangular format (9:16 or similar). This misrepresentation results in cut or cropped images, affecting the display of the reel's content.

**To Reproduce**
1- Use link-preview-js to preview this Facebook Reel URL: https://www.facebook.com/share/r/1492EKYUim/.
2- Observe the generated preview image in the response.

**Expected behavior**
The thumbnail image for Facebook Reels should maintain the original rectangular aspect ratio (typically 9:16) to display the content accurately.

**Additional context**
Example Response:

`{
  "charset": "\"utf-8\"",
  "contentType": "text/html",
  "description": "Get your Cat mask at viralhuntz.shop 🔥🐈‍⬛👻 #cat #catlovers #batman #cats #petlover #halloween #pet #pets #fyp #reels.",
  "favicons": ["https://static.xx.fbcdn.net/rsrc.php/yT/r/aGT3gskzWBf.ico"],
  "images": ["https://scontent.fcai21-2.fna.fbcdn.net/v/t15.5256-10/461678168_924153042876699_8645910664347760306_n.jpg?stp=c0.78.304.304a_dst-jpg_p180x540&_nc_cat=106&ccb=1-7&_nc_sid=656d3b&_nc_ohc=2jCUK8sHoocQ7kNvgG-mG0Q&_nc_zt=23&_nc_ht=scontent.fcai21-2.fna&_nc_gid=AqzsmnMMllPeIDh5qFGLuMt&oh=00_AYAJRSr_a0G7noLu1AoB2PzJDNAVIB3WRxKYVH-vSO6Xsw&oe=6733E1F8"],
  "mediaType": "video.other",
  "siteName": null,
  "title": "176K views · 7M reactions | Get your Cat mask at viralhuntz.shop 🔥🐈‍⬛👻 #cat #catlovers #batman #cats #petlover #halloween #pet #pets #fyp #reels | ",
  "url": "<img width="419" alt="Screenshot 2024-11-08 at 4 49 12 PM" src="https://github.com/user-attachments/assets/c227ec73-3d7e-4b35-a588-6f044858ea6c">",
  "videos": []
}`

Many thanks for your great work on this!

**Comment by ospfranco** [comment]
This library only returns the data on the html, if that's what you get it's what the page returns.
